/**
 * ODD classification, and its inverse.
 *
 * The scenario library records three coarse classes per template — visibility,
 * lighting and route — derived in the toolkit from the weather preset, the time
 * of day and the road geometry (`bhutan_sim/weather.py`,
 * `ScenarioParameters.route_class`). src/coverage.ts crosses the first two into
 * the ODD matrix.
 *
 * Reading those classes is only half of what a collection plan needs. Filling a
 * gap means going the other way: given the cell "fog at night on a hairpin
 * descent", which weather preset, which time of day and which curvature and
 * grade put a new scenario variant *in* that cell. That inverse lives here.
 *
 * Only the classification is ported, not the weather dictionaries: the Worker
 * never renders anything, so a preset is just a name plus the class it scores
 * as. `test/odd.test.ts` pins the table against every template in
 * `toolkit/scenarios/library.json`, which is generated by the Python that owns
 * the thresholds — so a change there fails the test rather than drifting.
 */

export type SourceKind = "sim" | "vehicle";

/**
 * visibility_class of each weather preset, as bhutan_sim.weather.visibility_class
 * scores the resolved dictionary (fog_density >= 40 → fog, precipitation >= 60 →
 * heavy_rain, any precipitation → rain, dust_storm > 0 → dust, wetness >= 50 → wet).
 */
export const PRESET_VISIBILITY: Record<string, string> = {
  clear_day: "clear",
  overcast: "clear",
  light_rain: "rain",
  heavy_rain: "heavy_rain",
  monsoon_storm: "heavy_rain",
  wet_road: "wet",
  valley_fog: "fog",
  dense_fog: "fog",
  low_sun: "clear",
  low_sun_haze: "clear",
  clear_night: "clear",
  wet_night: "wet",
  dust_haze: "dust",
};

/** lighting_class per time of day; mirrors weather.LIGHTING_CLASS. */
export const TIME_LIGHTING: Record<string, string> = {
  dawn: "low_light",
  day: "daylight",
  dusk: "low_light",
  night: "night",
};

export const TIMES_OF_DAY = ["dawn", "day", "dusk", "night"];

/**
 * Times of day a preset is physically consistent with. Most presets follow the
 * clock, but `low_sun*` encodes a sun a few degrees above the horizon and
 * `*_night` encodes one below it — `weather.resolve` keeps their own sun
 * altitude, so pairing them with any other time of day would describe a scene
 * the renderer cannot produce.
 */
export const PRESET_TIMES: Record<string, string[]> = {
  low_sun: ["dawn", "dusk"],
  low_sun_haze: ["dawn", "dusk"],
  clear_night: ["night"],
  wet_night: ["night"],
};

export function timesForPreset(preset: string): string[] {
  return PRESET_TIMES[preset] || TIMES_OF_DAY;
}

export function visibilityClassOf(preset: string): string {
  return PRESET_VISIBILITY[preset] || "clear";
}

export function lightingClassOf(timeOfDay: string): string {
  return TIME_LIGHTING[timeOfDay] || "daylight";
}

/** Coarse route class from curvature and grade; port of ScenarioParameters.route_class. */
export function routeClassOf(curvature: number, gradePct: number): string {
  const geometry = curvature >= 0.08 ? "hairpin" : curvature >= 0.03 ? "curve" : "straight";
  const slope = gradePct <= -6 ? "steep_descent" : gradePct >= 6 ? "steep_climb" : "flat";
  return `${geometry}_${slope}`;
}

export const GEOMETRIES = ["straight", "curve", "hairpin"];
export const SLOPES = ["flat", "steep_climb", "steep_descent"];

/** Curvature at the middle of each geometry band, in 1/m. */
const GEOMETRY_CURVATURE: Record<string, number> = { straight: 0.01, curve: 0.045, hairpin: 0.1 };
/** Grade at the middle of each slope band, in per cent. */
const SLOPE_GRADE: Record<string, number> = { flat: 0, steep_climb: 8, steep_descent: -8 };

export function splitRouteClass(routeClass: string): { geometry: string; slope: string } | null {
  for (const geometry of GEOMETRIES) {
    if (!routeClass.startsWith(`${geometry}_`)) continue;
    const slope = routeClass.slice(geometry.length + 1);
    if (SLOPES.includes(slope)) return { geometry, slope };
  }
  return null;
}

/**
 * Road geometry that lands in a route class. The returned curvature and grade
 * sit in the middle of their band, so `routeClassOf` on the result returns the
 * class asked for even after a sampler jitters them a little.
 */
export function geometryForRouteClass(routeClass: string): { road_curvature: number; grade_pct: number } | null {
  const parts = splitRouteClass(routeClass);
  if (!parts) return null;
  return { road_curvature: GEOMETRY_CURVATURE[parts.geometry], grade_pct: SLOPE_GRADE[parts.slope] };
}

export function routeClasses(): string[] {
  const out: string[] = [];
  for (const geometry of GEOMETRIES) for (const slope of SLOPES) out.push(`${geometry}_${slope}`);
  return out;
}

/**
 * Weather presets that score as `visibility` and can be rendered at `lighting`,
 * best first: a preset that encodes the lighting itself (`clear_night` for
 * night, `low_sun` for low light) beats one that merely tolerates it, because
 * it carries the wetness, glare and sun position that make the cell hard.
 * Empty when no preset reaches the cell — `snow` has none, so such a cell can
 * only be closed by driving.
 */
export function presetsFor(visibility: string, lighting: string): string[] {
  const candidates = Object.keys(PRESET_VISIBILITY).filter((preset) => {
    if (visibilityClassOf(preset) !== visibility) return false;
    return timesForPreset(preset).some((t) => lightingClassOf(t) === lighting);
  });
  return candidates.sort((a, b) => rank(a, lighting) - rank(b, lighting) || a.localeCompare(b));
}

/** 0 when the preset is specific to this lighting class, 1 when it just allows it. */
function rank(preset: string, lighting: string): number {
  const allowed = timesForPreset(preset);
  return allowed.every((t) => lightingClassOf(t) === lighting) ? 0 : 1;
}

/** Times of day for a preset that land in `lighting`, in daily order. */
export function timesFor(preset: string, lighting: string): string[] {
  return timesForPreset(preset).filter((t) => lightingClassOf(t) === lighting);
}
